### ISSUE TITLE
Integrate with travis, coverall

### ISSUE THREAD

**Issue by 1ambda** [oh-my-github/registry#35]

**Comment by tocology** [comment]
travis and coverall committed

**Comment by 1ambda** [comment]
Coverage is currently showed as `unknown`. I think we need to add [istanbul@v1.0.0-alpha.2](https://github.com/gotwarlost/istanbul)

For example, [slott: package.json](https://github.com/1ambda/slott/blob/935b798339e0aa6420acde811c7feeaced5a8e4f/package.json#L31)

**Comment by tocology** [comment]
@1ambda I also have a question about the `unknown` mark after I implemented Coverage. 

However, I don't think there is a problem at web-server's [package.json](https://github.com/oh-my-github/web-service/blob/develop/package.json) because you can also see the `istanbul` at line 55 in that dependency list. 

I just guess that it is related to whether `release` of our service has been completed or not. 

Is there any opinion about this issue? Please notify me. 

Thank :)

**Comment by tocology** [comment]
@1ambda If we need to implement the exact version of `istanbul`, I missed the option of `npm install`; --save-exact

Is that right for solving this problem?

**Comment by 1ambda** [comment]
@tocology 

I think `after_success` command in `.travis.yml` didn't work. You can check in [#92](https://travis-ci.org/oh-my-github/web-service)

There is a misspelled. `after_succuess` should be `after_success`. See [.travis.yml#5](https://github.com/oh-my-github/web-service/blob/bcebf421c65a7b7c3a185a17a0dff7fd6b9d17d8/.travis.yml#L5)

**Comment by tocology** [comment]
@1ambda 

What....the...

I'm so sorry for those mistakes..

It will be fixed at `develop` branch, so you all (with @njir) should update `develop` branch and keep going on your works.

Thanks, @1ambda

**Comment by tak-bro** [comment]
See 3ba814e
